### ISSUE TITLE
Clicking on set range from "data" does not work.

### ISSUE THREAD

**Issue by Andreas-Piter** [luhipi/insar-explorer#56]
with version v0.7.0

```
2025-01-13T17:29:00     WARNING    Traceback (most recent call last):
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\gui_controller.py", line 122, in setSymbologyRangeFromData
              message = self.insar_map.setSymbologyRangeFromData()
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\map_setting.py", line 50, in setSymbologyRangeFromData
              self.getDataRangeFromVectorLayer(layer, n_std)
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\map_setting.py", line 65, in getDataRangeFromVectorLayer
              min_max = layer.minimumAndMaximumValue(layer.fields().indexFromName(field_name))
             AttributeError: 'QgsVectorLayer' object has no attribute 'minimumAndMaximumValue'
```

**Comment by mahmud1** [comment]
Thanks, @Andreas-Piter.  
1. Did you restart QGIS after the upgrade to v0.7.0?  
2. How about 1xStd and 3xStd? Do they show the same error?
3. Are you experiencing the same issue with other shapefiles?

**Comment by Andreas-Piter** [comment]
Thanks for the suggestions to check.

1. I restarted QGIS.
2. 1x and 3x Std work.
3. I tested another dataset and it is the same problem.

I have the QGIS version: 3.16.3-Hannover. Could the problem be related to the version?

**Comment by mahmud1** [comment]
Yes, the issue is related to the QGIS version. Upgrading to QGIS >=3.20 should resolve it. The QgsVectorLayer.minimumAndMaximumValue function is only available in QGIS 3.20 and later ([Reference](https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.minimumAndMaximumValue)). 

For compatibility with older versions, we need to implement the following:

- [ ] Check the QGIS version at runtime
- [ ] Use minimumValue() and maximumValue() for QGIS <3.20.
- [ ] Maintain the current use of minimumAndMaximumValue for QGIS >=3.20.
Or simply
- [ ] use a try-except block to handle the issue.
